Refinement types
kind2-mc/kind2 pull request #1046
Opened 2024-01-25 16:12 UTC by lorchrob

Support refinement types

2024-03-25 15:39 UTC, daniel-larraz requested changes
I left several comments in the PR that you need to address. The PR branch has also conflicts that you must resolve.

2024-03-25 15:39 UTC, daniel-larraz commented on src/lustre/lustreNodeGen.ml
> +          (Some N.KGhost)
Are all these state variables really `KGhost` variables?

2024-03-25 20:12 UTC, lorchrob commented on src/lustre/lustreSyntaxChecks.mli
> +                            [> `LustreSyntaxChecksError of Lib.position * error_kind ]) result
Addressed

2024-03-25 20:12 UTC, lorchrob commented on src/lustre/lustreSyntaxChecks.ml
> +  | NodeCallInGlobalTypeDecl id -> "Illegal node call or choose operator in definition of global type '" ^ HString.string_of_hstring id ^ "'"
Addressed

2024-03-25 20:13 UTC, lorchrob commented on src/lustre/lustreSyntaxChecks.ml
> +  let check_merge: LA.expr -> ( [> `LustreSyntaxChecksWarning of Lib.position * warning_kind ] list, [> `LustreSyntaxChecksError of Lib.position * error_kind ])
Addressed

2024-03-25 20:13 UTC, lorchrob commented on src/lustre/lustreTypeChecker.mli
> +val type_check_infer_globals: tc_context -> LA.t -> (tc_context * [> `LustreTypeCheckerWarning of Lib.position * warning_kind ] list, [> error]) result
Addressed

2024-03-25 20:13 UTC, lorchrob commented on tests/regression/falsifiable/ref_type_ghost_var.lus
> +  --!! Does adding a guarantee cause a problem if this is an imported node?
Addressed

2024-03-25 20:13 UTC, lorchrob commented on tests/regression/success/ref_type_rec_project2.lus
> +  --!! This example should not fail (check recursively for base record type)
Addressed

2024-03-25 20:13 UTC, lorchrob commented on src/lustre/lustreAstHelpers.mli
> +val expr_contains_id : index -> expr -> bool
Addressed

2024-03-25 20:18 UTC, lorchrob commented on tests/ounit/lustre/lustreTypeChecker/nondeterministic_choice.lus
> +  y = any subtype { x: bool | x < 50 };
Addressed

2024-03-25 20:24 UTC, lorchrob commented on src/lustre/lustreAstDependencies.ml
> +      R.ok (connect_g_pos_biased true (List.fold_left union ad effective_vars2) i pos)
Addressed (I reverted the changes)

2024-03-25 20:32 UTC, lorchrob commented on src/lustre/lustreAstHelpers.ml
> +  | TVar _ | IntRange _ | Real _ | UserType _ | AbstractType _ | EnumType _ | History _ | TArr _ -> SI.empty
Addressed

2024-03-26 14:19 UTC, lorchrob commented on src/lustre/lustreAstHelpers.ml
> +  | _ -> false
Addressed.
Note: To handle `history(x)`, we need to look up the type of `x` using a helper function from `typeCheckerContext`. But, this causes a circular dependency. So, I moved these functions (along with `type_contains_subrange`) to `typeCheckerContext` (and also added an extra argument `ctx`)

2024-03-26 16:15 UTC, lorchrob commented on src/lustre/lustreAstDependencies.ml
> +  | RefinementType (_, _, expr) -> mk_graph_expr expr
Addressed

2024-03-26 16:16 UTC, lorchrob commented on src/lustre/lustreAstDependencies.ml
> +  | AliasType (pos, i, LA.RefinementType (_, (_, _, ty), _)) -> connect_g_pos (mk_graph_type ty) (HString.concat2 ty_prefix i) pos;
Addressed. (I checked, and your conjecture is correct)

2024-03-26 17:35 UTC, lorchrob commented on src/lustre/lustreTypeChecker.ml
> +let rec get_base_type ctx = function
I pushed a commit that refactors `expand_type` and related functions. It is a bit verbose and can maybe be simplified/refactored further, but the hope is that it increases clarity of the differences between the functions

2024-03-28 16:51 UTC, daniel-larraz commented on src/lustre/lustreAstDependencies.ml
> +  | Bool _ | Real _ | TVar _ | IntRange _ | UserType _ | AbstractType _ | EnumType _ | History _ | TArr _ -> []
`TArr` can also include node calls.

2024-04-02 14:07 UTC, lorchrob commented on src/lustre/lustreAstDependencies.ml
> +  | Bool _ | Real _ | TVar _ | IntRange _ | UserType _ | AbstractType _ | EnumType _ | History _ | TArr _ -> []
Addressed

2024-04-03 23:27 UTC, daniel-larraz approved these changes

2024-04-04 11:42 UTC, merged